version: "3.8"

services:
  server:
    build: ../server
    ports:
      - "8000:8000"
    env_file:
      - .\server\.env
    depends_on:
      - redis

  client:
    build: ../client
    ports:
      - "5173:5173"
    depends_on:
      - server

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  static_value:
  redis_data:
